// client/src/app/(auth)/login/page.tsx
import { LoginForm } from "@/lib/components/login-form";
import { getSession } from "@/lib/get-session";
import { redirect } from "next/navigation";

export default async function LoginPage() {
  const session = await getSession();

  if (session?.user) {
    redirect("/home");
  }

  const serverUrl = process.env.NEXT_PUBLIC_SERVER_URL;
  if (!serverUrl) return null;

  return (
    <div className="bg-background flex min-h-svh flex-col items-center justify-center gap-6 p-6">
      <div className="w-full max-w-sm">
        <LoginForm serverUrl={serverUrl} />
      </div>
    </div>
  );
}

// client-next/src/app/login/+page.svelte
<script lang="ts">
	import LoginForm from "@/lib/components/auth/login-form.svelte";

	let { data } = $props();

	// Client API:
  
	const formProps = $derived(data.form);
  const {SERVER_URL, IS_DEVELOPMENT } = data;
</script>

<div class="bg-background flex min-h-svh flex-col items-center justify-center gap-6 p-6 md:p-10">
	<div class="w-full max-w-sm">
		<LoginForm {formProps} {SERVER_URL} {IS_DEVELOPMENT} isLogin />
	</div>
</div>
