// client/src/routes/login/+page.svelte
<script lang="ts">
	import LoginForm from "$lib/components/auth/login-form.svelte";

	let { data } = $props();

	// Client API:
  
	const formProps = $derived(data.form);
  const {SERVER_URL, IS_DEVELOPMENT } = data;
</script>

<div class="bg-background flex min-h-svh flex-col items-center justify-center gap-6 p-6 md:p-10">
	<div class="w-full max-w-sm">
		<LoginForm {formProps} {SERVER_URL} {IS_DEVELOPMENT} isLogin />
	</div>
</div>

// client-next/src/app/login/page.tsx
import LoginForm from "@/lib/components/auth/LoginForm";

export default function page() {
  return (
    <div className="bg-background flex min-h-svh flex-col items-center justify-center gap-6 p-6 md:p-10">
      <div className="w-full max-w-sm">
        <LoginForm isLogin SERVER_URL={process.env.SERVER_URL ?? ""} />
      </div>
    </div>
  );
}
