// client/src/lib/components/common/Navbar.svelte
﻿<script lang="ts">
	import { Button } from '@/lib/components/ui/button';
	import type { User } from "@/lib/types";

	const { isSignup = false, user } = $props<{ isSignup?: boolean, user?: User }>();
</script>

<nav class={`flex navbar pt-10 px-10 ${isSignup ? "" : "md:px-96"}`}>
	<div class="flex-1">
		<a href="/" class="text-xl">
			Serene
		</a>
	</div>
	<div class="md:space-x-2">
    {#if user}
      <Button variant="default" href="/home">
        Go to Serene
      </Button>
    {:else}
       	<Button variant="default" href="/signup">
			Sign up
		</Button>
		<Button variant="ghost" href="/login">
			Or login
		</Button>
    {/if}
	
	</div>
</nav>

// client-next/src/lib/components/common/Navbar.tsx
﻿	import { Button } from '@/lib/components/ui/button';
import type { User } from "@/lib/types";
import Link from "next/link";

export default function Navbar({isSignup = false, user}: { isSignup?: boolean, user?: User }) {
  return (
    <nav className={`flex navbar pt-10 px-10 ${isSignup ? "" : "md:px-96"}`}>
      <div className="flex-1">
        <a href="/" className="text-xl">
          Serene
        </a>
      </div>
      <div className="md:space-x-2">
        {user && (
          <Button variant="default">
            <Link href="/home">Go to Serene</Link>
          </Button>)
        }
        {!user && (
            <><Button variant="default">
          <Link href="/signup">Sign up</Link>
        </Button>
        <Button variant="ghost">
          <Link href="/login">Or login</Link>
        </Button></>
      )}
      </div>
    </nav>

  )
}
