// client/src/lib/components/forms/form-select.svelte
<script lang="ts">
	import * as Select from "$lib/components/ui/select/index.js";

	type Props = {
		name: string;
    value: string;
		items: {
			value: string;
			label: string;
		}[];
	};

	let { name, items, value = $bindable("") }: Props = $props();

	const triggerContent = $derived(
		items.find((f) => f.value === value)?.label ?? `Select a ${name}`
	);
</script>

<Select.Root type="single" {name} bind:value>
	<Select.Trigger class="w-full">
		{triggerContent}
	</Select.Trigger>
	<Select.Content>
		<Select.Group>
			<Select.Label>items</Select.Label>
			{#each items as item (item.value)}
				<Select.Item value={item.value} label={item.label}>
					{item.label}
				</Select.Item>
			{/each}
		</Select.Group>
	</Select.Content>
</Select.Root>

// client-next/src/lib/components/forms/FormSelect.tsx
"use client";

import * as React from "react";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from "@/lib/components/ui/select";

type Item = {
  value: string;
  label: string;
};

type Props = {
  name: string;
  value?: string;
  items: Item[];
  onChange?: (value: string) => void;
};

export function AppSelect({ name, value, items, onChange }: Props) {
  return (
    <Select value={value} onValueChange={onChange}>
      <SelectTrigger className="w-full">
        <SelectValue placeholder={`Select a ${name}`} />
      </SelectTrigger>
      <SelectContent>
        <SelectGroup>
          <SelectLabel>{name}</SelectLabel>
          {items.map((item) => (
            <SelectItem key={item.value} value={item.value}>
              {item.label}
            </SelectItem>
          ))}
        </SelectGroup>
      </SelectContent>
    </Select>
  );
}
