// client/src/lib/components/login-form.tsx
"use client";

import { useForm } from "@tanstack/react-form";
import { GalleryVerticalEnd } from "lucide-react";
import { useState } from "react";

import { authClient } from "@/lib/auth";
import { Button } from "@/lib/components/ui/button";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/lib/components/ui/form";
import { Input } from "@/lib/components/ui/input";
import { apiFetch } from "@/lib/helpers/api-fetch";
import { cn } from "@/lib/utils";
import Link from "next/link";
import { z } from "zod";

const emailSchema = z.object({
  email: z.email(),
});

const authSchema = z.object({
  email: z.email(),
  password: z.string().min(1, "Password is required"),
});

interface Props {
  serverUrl: string;
}

export function LoginForm({
  className,
  serverUrl,
  ...props
}: React.ComponentProps<"div"> & Props) {
  const [step, setStep] = useState(1);
  const [email, setEmail] = useState("");
  const [loginError, setLoginError] = useState("");

  const form = useForm({
    defaultValues: {
      email: "",
      password: "",
    },
    validators: {
      onChange: authSchema,
    },

    onSubmit: async ({ value }) => {
      setLoginError("");
      try {
        const result = await authClient.signIn.email({
          email: email,
          password: value.password,
        });
        if (result.error) {
          setLoginError(result.error.message || "Invalid email or password");
        } else {
          const onboarding = await apiFetch(`/users/onboarding`).then((r) =>
            r.json()
          );

          if (onboarding.completed) {
            window.location.href = "/home";
          } else {
            window.location.href = "/onboarding";
          }
        }
      } catch (error) {
        setLoginError("Login failed. Please try again.");
      }
    },
  });

  const handleEmailSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const emailValue = form.getFieldValue("email");
    const emailValidation = emailSchema.safeParse({ email: emailValue });

    if (emailValidation.success) {
      const res = await fetch(
        `${serverUrl}/users/exists/${encodeURIComponent(emailValue)}`
      );
      const data = await res.json();

      if (data.exists) {
        setEmail(emailValue);
        setStep(2);
      } else {
        console.error(data);
        setLoginError(
          "No accounts associated with this email, maybe try signing up?"
        );
      }
    }
  };

  const handleBack = () => {
    setStep(1);
  };

  return (
    <div className={cn("flex flex-col gap-6", className)} {...props}>
      <div className="flex flex-col items-center gap-2 text-center">
        <div className="flex flex-col items-center gap-2 font-medium">
          <div className="flex size-8 items-center justify-center rounded-md">
            <GalleryVerticalEnd className="size-6" />
          </div>
        </div>
        <h1 className="text-xl font-bold">
          {step === 1 ? "Welcome Back" : "Enter Password"}
        </h1>
        <FormDescription>
          {step === 1 ? (
            <>
              Don&apos;t have an account? <Link href="/signup">Sign up</Link>
            </>
          ) : (
            <>
              Welcome back, <span className="font-medium">{email}</span>
            </>
          )}
        </FormDescription>
      </div>

      <Form>
        {step === 1 ? (
          <form onSubmit={handleEmailSubmit} className="space-y-4">
            <form.Field name="email">
              {(field) => (
                <FormField name={field.name}>
                  <FormItem>
                    <FormLabel>Email</FormLabel>
                    <FormControl>
                      <Input
                        type="email"
                        placeholder="m@example.com"
                        value={field.state.value}
                        onChange={(e) => field.handleChange(e.target.value)}
                      />
                    </FormControl>
                    {!field.state.meta.isValid && field.state.meta.isTouched
                      ? field.state.meta.errors.map((error) => (
                          <FormMessage
                            role="alert"
                            key={error?.message || "error"}
                          >
                            {error?.message}
                          </FormMessage>
                        ))
                      : null}
                  </FormItem>
                </FormField>
              )}
            </form.Field>

            {loginError && (
              <div className="text-sm text-red-600 text-center">
                {loginError}
              </div>
            )}
            <Button type="submit" className="w-full">
              Continue
            </Button>
          </form>
        ) : (
          <form
            onSubmit={(e) => {
              e.preventDefault();
              form.handleSubmit();
            }}
            className="space-y-4"
          >
            <form.Field name="password">
              {(field) => (
                <FormField name={field.name}>
                  <FormItem>
                    <FormLabel>Password</FormLabel>
                    <FormControl>
                      <Input
                        type="password"
                        placeholder="Enter your password"
                        value={field.state.value}
                        onChange={(e) => field.handleChange(e.target.value)}
                      />
                    </FormControl>
                    {!field.state.meta.isValid && field.state.meta.isTouched
                      ? field.state.meta.errors.map((error) => (
                          <FormMessage
                            role="alert"
                            key={error?.message || "error"}
                          >
                            {error?.message}
                          </FormMessage>
                        ))
                      : null}
                  </FormItem>
                </FormField>
              )}
            </form.Field>

            {loginError && (
              <div className="text-sm text-red-600 text-center">
                {loginError}
              </div>
            )}

            <div className="flex gap-2">
              <Button
                type="button"
                variant="outline"
                onClick={handleBack}
                className="flex-1"
              >
                Back
              </Button>
              <form.Subscribe selector={(state) => state.isSubmitting}>
                {(isSubmitting) => (
                  <Button
                    type="submit"
                    className="flex-1"
                    disabled={isSubmitting}
                  >
                    {isSubmitting ? "Logging in..." : "Login"}
                  </Button>
                )}
              </form.Subscribe>
            </div>
          </form>
        )}
      </Form>

      <FormDescription className="px-6 text-center">
        By clicking continue, you agree to our{" "}
        <Link href="/terms">Terms of Service</Link> and{" "}
        <Link href="/privacy">Privacy Policy</Link>.
      </FormDescription>
    </div>
  );
}

// client-next/src/lib/components/auth/login-form.svelte
<script lang="ts">
	import { goto } from "$app/navigation";
	import { page } from "$app/stores";
	import { loginSchema, signUpSchema, type LoginFormSchema } from "@/lib/components/auth/formSchema";
	import GoogleIcon from "@/lib/components/auth/google-icon.svelte";
	import { Button } from "@/lib/components/ui/button";
	import * as Form from "@/lib/components/ui/form";
	import { Input } from "@/lib/components/ui/input";
	import { cn, type WithElementRef } from "@/lib/utils.js";
	import GalleryVerticalEndIcon from "@lucide/svelte/icons/gallery-vertical-end";
	import type { HTMLAttributes } from "svelte/elements";
	import SuperDebug, { superForm, type SuperValidated } from "sveltekit-superforms";
	import { zod4Client } from "sveltekit-superforms/adapters";
	import type { Infer } from "zod/v4";

	type Props = WithElementRef<HTMLAttributes<HTMLDivElement>> & {
		formProps: SuperValidated<Infer<LoginFormSchema>>;
		SERVER_URL: string;
		IS_DEVELOPMENT: boolean;
		isLogin?: boolean;
	};

	let {
		class: className,
		formProps,
		SERVER_URL,
		isLogin = false,
		IS_DEVELOPMENT,
		...restProps
	}: Props = $props();

	const id = $props.id();
  let loadingFormResult = $state(false);
	// Client API:
	const form = superForm(formProps, {
    onResult(event) {
      loadingFormResult = false;
      if (event.result.type === "success") {
        goto("/login/callback");
      }

    },
    onSubmit() {
      loadingFormResult = true;
    },
	});

	const { form: formData, errors, constraints, message, enhance } = form;

	const origin = $page.url.origin;
</script>

{#if $message}<h3>{$message}</h3>{/if}

<form method="POST" use:enhance class={cn("flex flex-col gap-6", className)}>
	<div class="flex flex-col gap-6">
		<div class="flex flex-col items-center gap-2">
			<a href="##" class="flex flex-col items-center gap-2 font-medium">
				<div class="flex size-8 items-center justify-center rounded-md">
					<GalleryVerticalEndIcon class="size-6" />
				</div>
				<span class="sr-only">Serene</span>
			</a>
			<h1 class="text-xl font-bold">
				{#if isLogin}
					Login to Serene
				{:else}
					Sign Up for Serene
				{/if}
			</h1>
			{#if isLogin}
				<div class="text-center text-sm">
					Don&apos;t have an account?
					<a href="/signup" class="underline underline-offset-4"> Sign up </a>
				</div>
			{:else}
				<div class="text-center text-sm">
					Already have an account?
					<a href="/login" class="underline underline-offset-4"> Login </a>
				</div>
			{/if}
		</div>
		<div class="flex flex-col gap-6">
			<div class="grid gap-3">
				<Form.Field {form} name="email">
					<Form.Control>
						{#snippet children({ props }: any)}
							<Form.Label>Email</Form.Label>
							<Input placeholder="me@example.com" {...props} bind:value={$formData.email} />
						{/snippet}
					</Form.Control>
					<Form.Description>The email you will use for logging in</Form.Description>
					<Form.FieldErrors />
				</Form.Field>
			</div>
			<div class="grid gap-3">
				<Form.Field {form} name="password">
					<Form.Control>
						{#snippet children({ props }: any)}
							<Form.Label>Password</Form.Label>
							<Input {...props} type="password" bind:value={$formData.password} />
						{/snippet}
					</Form.Control>
					<Form.Description>What you'll be using to secure your account</Form.Description>
					<Form.FieldErrors />
				</Form.Field>
			</div>
			<Form.Button type="submit" class="w-full"
				>{#if isLogin}
					Login
				{:else}
					Sign Up
				{/if}
        {#if loadingFormResult}
          Loading
        {/if}
			</Form.Button>
		</div>
		<div
			class="after:border-border relative text-center text-sm after:absolute after:inset-0 after:top-1/2 after:z-0 after:flex after:items-center after:border-t"
		>
			<span class="bg-background text-muted-foreground relative z-10 px-2"> Or </span>
		</div>
		<div class="grid gap-4">
			<Button
				variant="outline"
				type="button"
				class="w-full"
				href={`${SERVER_URL}/auth/login/google?returnUrl=${origin}/login/callback`}
			>
				<GoogleIcon />
				Continue with Google
			</Button>
		</div>
	</div>
	<div
		class="text-muted-foreground *:[a]:hover:text-primary *:[a]:underline *:[a]:underline-offset-4 text-balance text-center text-xs"
	>
		By clicking continue, you agree to our <a href="##">Terms of Service</a>
		and <a href="##">Privacy Policy</a>.
	</div>
</form>
{#if IS_DEVELOPMENT}
	<SuperDebug data={{formData, errors}} />
{/if}

<style>
	.invalid {
		color: var(--color-red-500);
	}
</style>
