// client/src/lib/components/sidebar-header.svelte
<script lang="ts">
	import SereneLogo from "@/lib/components/common/serene-logo.svelte";
	import * as DropdownMenu from "@/lib/components/ui/dropdown-menu/index.js";
	import * as Sidebar from "@/lib/components/ui/sidebar/index.js";
	import { useSidebar } from "@/lib/components/ui/sidebar/index.js";
	import { Ribbon } from "@lucide/svelte";
	import ChevronsUpDownIcon from "@lucide/svelte/icons/chevrons-up-down";
	import GalleryVerticalEndIcon from "@lucide/svelte/icons/gallery-vertical-end";
	import PlusIcon from "@lucide/svelte/icons/plus";

	const sidebar = useSidebar();
</script>

<Sidebar.Menu>
	<Sidebar.MenuItem >
		<Sidebar.MenuButton size="lg">
			{#snippet child({ props })}
				<a href="/home" {...props}>
					<SereneLogo />
				</a>
			{/snippet}
		</Sidebar.MenuButton>
	</Sidebar.MenuItem>
</Sidebar.Menu>

// client-next/src/lib/components/SidebarHeader.tsx
// SidebarMenu.tsx
"use client";

import React from "react";
import SereneLogo from "@/lib/components/common/SereneLogo"; // React version of your logo
import {
  Sidebar,
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuButton,
  useSidebar,
} from "@/lib/components/ui/sidebar"; // React version of your sidebar
import { Ribbon, ChevronsUpDown, GalleryVerticalEnd, Plus } from "lucide-react";

export default function SidebarMenuComponent() {
  const sidebar = useSidebar();

  return (
    <Sidebar>
      <SidebarMenu>
        <SidebarMenuItem>
          <SidebarMenuButton size="lg">
            <a href="/home">
              <SereneLogo />
            </a>
          </SidebarMenuButton>
        </SidebarMenuItem>
      </SidebarMenu>
    </Sidebar>
  );
}
