// apps/client/src/lib/components/common/sidebar/app-sidebar.tsx
"use client";

import AppSidebarHeader from "@/lib/components/common/sidebar/sidebar-header";
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarHeader,
} from "@/lib/components/ui/sidebar";
import { Home, Library, ListMusic, Pencil, TrendingUp } from "lucide-react";
import * as React from "react";

import { User } from "@serene/shared/types";
import NavMain from "./nav-main";
import { NavUser } from "./nav-user";

const data = {
  user: {
    name: "shadcn",
    email: "m@example.com",
    image: "/avatars/shadcn.jpg",
  },
  navMain: [
    { title: "Home", url: "/home", icon: Home },
    { title: "Reflect", url: "/home/reflect", icon: Pencil, isActive: true },
    { title: "Ambience", url: "/home/ambience", icon: ListMusic },
    { title: "Trends", url: "/home/trends", icon: TrendingUp },
    { title: "Content Library", url: "/home/library", icon: Library },
  ],
};

type SidebarLayoutProps = React.ComponentProps<typeof Sidebar> & {
};

export default function AppSidebar({ ...props }: SidebarLayoutProps) {
  return (
    <Sidebar collapsible="icon" {...props}>
      <SidebarHeader>
        <AppSidebarHeader />
      </SidebarHeader>
      <SidebarContent className="flex flex-col items-center h-full justify-center">
        <NavMain items={data.navMain} />
      </SidebarContent>
      <SidebarFooter>
        <NavUser/>
      </SidebarFooter>
    </Sidebar>
  );
}

// client/src/lib/components/app-sidebar.svelte
<script lang="ts" module>
	import { Home, Library, ListMusic, Pencil, TrendingUp } from "@lucide/svelte/icons";

	const data = $derived({
		user: {
			name: "shadcn",
			email: "m@example.com",
			avatar: "/avatars/shadcn.jpg"
		},
		navMain: [
      {
        title: "Home",
        url: "/home",
        icon: Home
      },
			{
				title: "Reflect",
				url: "/home/reflect",
				icon: Pencil,
				isActive: true
			},
			{
				title: "Ambience",
				url: "/home/ambience",
				icon: ListMusic
			},
			{
				title: "Trends",
				url: "/home/trends",
				icon: TrendingUp
			},
			{
				title: "Content Library",
				url: "/home/library",
				icon: Library
			}
		]
	});
</script>

<script lang="ts">
  



	import * as Sidebar from "$lib/components/ui/sidebar/index.js";
	import type { ComponentProps } from "svelte";
	import NavMain from "./nav-main.svelte";
	import NavUser from "./nav-user.svelte";
	import SidebarHeader from "./sidebar-header.svelte";

	let {
		ref = $bindable(null),
		collapsible = "icon",
		...restProps
	}: ComponentProps<typeof Sidebar.Root>  = $props();
</script>

<Sidebar.Root {collapsible} {...restProps} class="border-sidebar-primary">
	<Sidebar.Header>
		<SidebarHeader />
	</Sidebar.Header>
	<Sidebar.Content class="flex flex-col h-full justify-center">
		<NavMain items={data.navMain} />
	</Sidebar.Content>
	<Sidebar.Footer>
		<NavUser />
	</Sidebar.Footer>
</Sidebar.Root>
