// client/src/lib/components/common/sidebar/sidebar-header.tsx
// SidebarMenu.tsx
"use client";

import SereneLogo from "@/lib/components/common/serene-logo"; // React version of your logo
import {
  DropdownMenu,
  DropdownMenuTrigger,
} from "@/lib/components/ui/dropdown-menu";
import {
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  useSidebar,
} from "@/lib/components/ui/sidebar"; // React version of your sidebar
import { useIsMobile } from "@/lib/hooks/use-mobile";

export default function SidebarMenuComponent() {
  const sidebar = useSidebar();
  const isMobile = useIsMobile();

  return (
    <SidebarMenu>
      <SidebarMenuItem>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <SidebarMenuButton
              size="lg"
              className="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
            >
              <div className="flex aspect-square size-8 items-center justify-center rounded-lg">
                <SereneLogo noText sidebar />
              </div>
              <div className="grid flex-1 text-left text-sm leading-tight">
                <SereneLogo noLogo />
              </div>
            </SidebarMenuButton>
          </DropdownMenuTrigger>
        </DropdownMenu>
      </SidebarMenuItem>
    </SidebarMenu>
  );
}

// client/src/lib/components/sidebar-header.svelte
<script lang="ts">
	import * as DropdownMenu from "$lib/components/ui/dropdown-menu/index.js";
	import * as Sidebar from "$lib/components/ui/sidebar/index.js";
	import { useSidebar } from "$lib/components/ui/sidebar/index.js";
	import { Ribbon } from "@lucide/svelte";
	import ChevronsUpDownIcon from "@lucide/svelte/icons/chevrons-up-down";
	import GalleryVerticalEndIcon from "@lucide/svelte/icons/gallery-vertical-end";
	import PlusIcon from "@lucide/svelte/icons/plus";

	const sidebar = useSidebar();
</script>

<Sidebar.Menu>
	<Sidebar.MenuItem >
		<Sidebar.MenuButton size="lg">
			{#snippet child({ props })}
				<a href="##" {...props}>
					<div
						class="text-sidebar-primary flex aspect-square items-center justify-center rounded-lg"
					>
						<Ribbon  />
					</div>
          <span class="font-medium">Serene</span>
				</a>
			{/snippet}
		</Sidebar.MenuButton>
	</Sidebar.MenuItem>
</Sidebar.Menu>
